version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: flashfast_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    container_name: flashfast_redis
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: flashfast_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
